- ase/sw/mqueue_ops.c
Resolves the following error:
```
opae-sim/ase/sw/mqueue_ops.c:133:9: error: ‘%s’ directive output may be truncated writing up to 4535 bytes into a region of size 255 [-Werror=format-truncation=]
```
> ase/mqueue: fix compilation with gcc >= 9

- ase/api/CMakeLists.txt
libase.so is missing the dependency, so at runtime it will give an error about unknown symbol `shm_open`.
> cmake: add missing librt dependency

- ase/Makefile
This patch fixes the following error for me:
```
cd work ; gcc  -g -m32 -fPIC -D SIM_SIDE=1 -I /sim/sw/ -D SIMULATOR=QUESTA -D FPGA_PLATFORM_DISCRETE -Wall -Wformat -Wformat-security -O2 -D_FORTIFY_SOURCE=2 -fstack-protector-all -I /opt/intelFPGA_pro/quartus_19.2.0b57/modelsim_ase/include/ -c /sim/sw/ase_ops.c /sim/sw/ase_strings.c /sim/sw/ipc_mgmt_ops.c /sim/sw/ase_shbuf.c /sim/sw/protocol_backend.c /sim/sw/pcie_tlp_debug.c /sim/sw/pcie_tlp_stream.c /sim/sw/tstamp_ops.c /sim/sw/mqueue_ops.c /sim/sw/error_report.c /sim/sw/linked_list_ops.c /sim/sw/randomness_control.c  || exit 1
/sim/sw/pcie_tlp_debug.c: In function ‘fprintf_tlp_payload’:
/sim/sw/pcie_tlp_debug.c:108:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
for (int i = n_dwords - 1; i >= 0; i -= 1)
^ …
```
> Add `-std=c99` to `CC_OPT`

- ase/api/src/common.c
Use OPAE_DEFAULT_LOGLEVEL instead.
> ase: FPGA_DEFAULT_LOGLEVEL is deprecated

- ase/api/src/common.c
- ase/api/src/enum.c
- ase/api/src/open.c
- ase/api/src/token.h
- ase/api/src/types_int.h
See opae-libs/include/opae/types.h:fpga_token_header.
Implementing the common token header format allows filtering/
properties to discern the parent/child token relationship
across plugin boundaries.
> api: adopt OPAE common token header

- ase/sw/ase_common.h
- ase/sw/error_report.c
- ase/sw/mqueue_ops.c
Place global variable definitions in the .c file and extern
statement in the .h to avoid multiple variable def's.
https://github.com/OPAE/opae-sdk/issues/2289
> sw: resolve github issue 2289

- ase/api/CMakeLists.txt
This was breaking on RHEL8. It was finding the OPAE SDK's config.h
rather than ASE's config.h. Move the ASE search path to the top to
fix.
> api: fix the include search order

- ase/CMakeLists.txt
- ase/api/src/common_int.h
- ase/api/src/enum.c
- ase/api/src/plugin.c
The following changes were recently made to what OPAE installs:
* install plugin related headers in include/opae/plugin
* opae_int.h
* adapter.h
* props.h
* install plugin.h in include /opae that includes the aforementioned
headers
* install cmake config files in /usr/lib/opae-<version>
With these changes, ASE's plugin implementation needs to be changed to
reflect the new includes as well as to use cmake find_package to find
OPAE. If OPAE is installed in a non-standard path then one can set
CMAKE_PREFIX_PATH environment to point to that path prior to running
cmake config in this project.
Example:
OPAE is installed using prefix /some/arbitrary/path.
Then, to configure cmake for this project, run:
``` bash
git clone https://github.com/OPAE/opae-sim.git
cd opae-sim
mkdir build …
```
> build: update how ase finds opae

- ase/api/src/enum.c
- ase/api/src/token.h
Implement 2 new properties - subsystem_vendor and subsystem_device.
These two uniquely identify a device, even though vendor/device ID
may not change from one generation to the next.
> prop: implement subsystem_vendor, subsystem_device

- ase/readme.md
This readme currently contains a brief description of the plugin but
also includes instructions on how to find opae for building ase.
Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>
> doc: add readme to ase directory

- ase/api/CMakeLists.txt
Now that opae-sdk devel files includes cmake functions to generate an
opae-c API implementation, use it in ase/api to create a shared library,
opae-c-ase, that will always load ase plugin.
Signed-off-by: Rodrigo Rojo <rodrigo.rojo@intel.com>
> ase: use cmake function to create opae-c-ase

- ase/sw/app_backend.c
Broken pipe caused by ASE's MMIO respond coming in between app backend initializing
and deinitialing, when the named pipes are closed and not monitored. This change makes
`fpgaClose()` wait for ASE's responses to all outstanding MMIO requests.
> sw: resolve write broken_pipe issue when running ASE in regression mode

- ase/sw/protocol_backend.c
The app end's `session_deinit` function will try to send `ASE_SIMKILL` command to the protocol end, and wait for the protocol end's response. When the last run of the DUT finished in regression mode, the protocol end somehow doesn't send response to app end's `ASE_SIMKILL`, causing the app end process not terminating, which then leads to lingering .nfsxxxx files in the work directory. This causes problems in subsequent run of ASE if the user doesn't clean up the .nfsxxxx files by killing the app end process.
This change attempts to fix this issue by sending response to app end's `ASE_SIMKILL` in `start_simkill_countdown`. The response is sent in this function instead of in `ase_listener` in order to handle ctrl-C signals sent in regression mode.
> sw: make sure app process exits cleanly after regression mode run

- ase/Makefile
- ase/scripts/generate_ase_environment.py
A new rtl_src_config option creates separate source file lists for Verilog and VHDL modes. Update the simulator environment generator to match.
> Use rtl_src_config --sim-vhdl to parse VHDL source lists

- ase/api/src/mmio.c
- ase/sw/ase_common.h
An N6000 FIM that expands the MMIO address space to 1GB was created, therefore, extending software MMIO address space correspondingly.
> sw: extend MMIO address space to 1GB

- ase/api/src/ase.h
- ase/api/src/buffer.c
- ase/api/src/plugin.c
- ase/api/src/types_int.h
Allocates a PASID with the same interface as OPAE. Does not yet emulate PCIe ATS/PRS with PASID.
> Feature - Add fpgaBindSVA() to match OPAE

- ase/api/CMakeLists.txt
- ase/sw/app_backend.c
- ase/sw/ase_host_memory.c
- ase/sw/ase_host_memory.h
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_debug.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_hdr.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_stream.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_stream.h
Update ASE's IOMMU emulation to support two spaces: IOVA and PA. With the update, IOVAs are now assigned using the same library as the real OPAE SDK and vfio. Pinned pages now go through this path, using IOVAs assigned by the library.
For PCIe ATS, ASE now maintains a simulated physical address space that is separate from IOVA. This commit contains the bare minimum for detecting a translation request and responding with a single PA. PRS and invalidation are not yet emulated. munmap() is not tracked yet.
> Initial support for PCIe ATS emulation

- ase/sw/app_backend.c
- ase/sw/ase_common.h
- ase/sw/ase_host_memory.c
- ase/sw/ase_host_memory.h
- ase/sw/mqueue_ops.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_debug.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_hdr.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_stream.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_stream.h
- ase/sw/pcie_ss_tlp/pcie_tlp_func.h
- ase/sw/protocol_backend.c
Two new PCIe messages supported: page request and page request group response. ASE is operating in user space, so the normal PRS allocation of backing storage for a page is invisible. The PRS message does, however, indicate whether a VA is mapped in the address space.
PIM test suite
> [Update] Add emulation of PCIe PRS request and response

- ase/api/CMakeLists.txt
- ase/scripts/with_ase
- ase/sw/app_backend.c
- ase/sw/ase_host_memory.c
- ase/sw/ase_host_memory.h
- ase/sw/ase_pcie_ats.c
- ase/sw/ase_pcie_ats.h
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_debug.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_stream.c
- ase/sw/preload/mmap_hooks.c
- New LD_PRELOAD library that detects munmap() calls a hook in ASE to trigger invalidation. The LD_PRELOAD is set by "with_ase".
- Generate ATS invalidation requests, handle responses.
- Timeout when invalidation responses don't arrive, raising an error. The same error on HW can crash a host.
> [Feature] - Add emulation of PCIe ATS invalidation

- ase/api/src/buffer.c
- ase/api/src/close.c
- ase/api/src/enum.c
- ase/api/src/mmio.c
- ase/api/src/open.c
- ase/api/src/token.h
- ase/api/src/types_int.h
- ase/sw/app_backend.c
- ase/sw/ase_common.h
- ase/sw/ase_host_memory.c
- ase/sw/ase_host_memory.h
- ase/sw/axis_pcie_tlp/pcie_tlp_stream.c
- ase/sw/pcie_ss_tlp/pcie_ss_tlp_stream.c
- ase/sw/protocol_backend.c
PCIe SS versions of ASE already include a PF/VF MUX. This update emulates AFU ports as VFs of PF0.
- Port discovery enumerates AFU UUIDs on all VFs.
- The standard OPAE UUID search will find an AFU on any VF.
- Multiple VFs may be open simultaneously.
- IOVA mappings are associated with particular VFs.
- Remove IOVA mappings for at fpgaClose().
- Print emulated B:D:F and GUID of discovered AFUs.
- Legacy CCI-P and OFS EA variants remain limited to one port.
host_exerciser, afu_examples, PIM tests
> [Feature] - Add multi-VF support to ASE
